# Generated by Django 5.2.5 on 2026-09-07 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_api', '0008_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('legacy_id', models.BigIntegerField(blank=True, db_index=True, help_text='Identifier of this tag in the system it was migrated from. Set by migration tooling, not by the API.', null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, default='', help_text='Post body as HTML.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('featured_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='blog/featured-images/')),
                ('featured_image_alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('seo_title', models.CharField(blank=True, default='', help_text='Overrides the title in search results. Falls back to the post title when empty.', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='', help_text='Meta description shown in search results.')),
                ('seo_focus_keyword', models.CharField(blank=True, default='', help_text='Primary keyword the post targets.', max_length=255)),
                ('seo_noindex', models.BooleanField(default=False, help_text='Ask search engines not to index this post.')),
                ('seo_nofollow', models.BooleanField(default=False, help_text='Ask search engines not to follow links in this post.')),
                ('legacy_id', models.BigIntegerField(blank=True, db_index=True, help_text='Identifier of this post in the system it was migrated from. Set by migration tooling, not by the API.', null=True, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='blog_posts', to='category_api.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog_api.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('publish_blog_post', 'Can publish blog post'), ('unpublish_blog_post', 'Can unpublish blog post')],
            },
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['name'], name='blog_api_bl_name_2fd550_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['is_active'], name='blog_api_bl_is_acti_d5ba35_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title'], name='blog_api_bl_title_db184d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_at'], name='blog_api_bl_status_91c0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', 'status'], name='blog_api_bl_author__e12258_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'PUBLISHED')), models.Q(('published_at__isnull', True), ('status', 'DRAFT')), _connector='OR'), name='blog_post_published_at_matches_status'),
        ),
    ]
