# Generated by Django 5.2.5 on 2026-09-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0013_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='\n            Identifier of this brand in the system it was migrated from.\n        ', null=True, unique=True),
        ),
    ]
