# Generated by Django 5.2.5 on 2026-09-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0015_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_focus_keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
