# Generated by Django 5.2.5 on 2026-09-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0016_brand_seo_description_brand_seo_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
    ]
