# Generated by Django 5.2.5 on 2026-09-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0017_product_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['view_count'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
