# Generated by Django 5.2.5 on 2026-09-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0018_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-view_count', 'id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
