# Generated by Django 5.2.5 on 2026-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0019_alter_product_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brand',
            new_name='product_api_name_12f212_idx',
            old_name='brands_name_c58671_idx',
        ),
        migrations.RenameIndex(
            model_name='brand',
            new_name='product_api_is_acti_066ccb_idx',
            old_name='brands_is_acti_101dba_idx',
        ),
        migrations.RenameIndex(
            model_name='brand',
            new_name='product_api_created_9c2cf6_idx',
            old_name='brands_created_5b9afc_idx',
        ),
        migrations.RenameIndex(
            model_name='brand',
            new_name='product_api_display_1003d8_idx',
            old_name='brands_display_88dd5d_idx',
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
    ]
