# Generated by Django 5.2.5 on 2026-10-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emaillog',
            table=None,
        ),
    ]
