# Generated by Django 5.2.5 on 2026-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0002_alter_emaillog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
