# Generated by Django 5.2.5 on 2026-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0003_emaillog_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Sent'), (4, 'Failed')], db_index=True, default=1),
        ),
    ]
