# Generated by Django 5.2.5 on 2026-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
