# Generated by Django 5.2.5 on 2026-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_alter_user_email_user_unique_user_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
