# Generated by Django 5.2.5 on 2026-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
