# Generated by Django 5.2.5 on 2026-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0009_category_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
