# Generated by Django 5.2.5 on 2026-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0010_category_short_description_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'permissions': [('mark_category_as_menu', 'Can mark category as menu'), ('remove_category_from_menu', 'Can remove category from menu'), ('mark_category_as_featured', 'Can mark category as featured'), ('remove_category_from_featured', 'Can remove category from featured')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='featured_display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_icon',
            field=models.FileField(blank=True, null=True, upload_to='categories/featured-icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
