# Generated by Django 5.2.5 on 2026-09-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0011_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
