# Generated by Django 5.2.5 on 2026-10-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0007_alter_chartofaccount_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='account_api_code_e60026_idx',
            old_name='chart_of_ac_code_29cb81_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='account_api_name_953112_idx',
            old_name='chart_of_ac_name_ad5405_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='account_api_account_0e8253_idx',
            old_name='chart_of_ac_account_a9e0ce_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='account_api_opening_7f4bb0_idx',
            old_name='chart_of_ac_opening_59c3e4_idx',
        ),
        migrations.AlterModelTable(
            name='chartofaccount',
            table=None,
        ),
    ]
