# Generated by Django 5.2.5 on 2026-09-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin_api', '0002_origin_parent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='origin',
            new_name='origin_api__name_4df387_idx',
            old_name='origins_name_50aa12_idx',
        ),
        migrations.RenameIndex(
            model_name='origin',
            new_name='origin_api__is_acti_0b10ac_idx',
            old_name='origins_is_acti_6ac6df_idx',
        ),
        migrations.RenameIndex(
            model_name='origin',
            new_name='origin_api__created_8d5bd6_idx',
            old_name='origins_created_0eed52_idx',
        ),
        migrations.AlterModelTable(
            name='origin',
            table=None,
        ),
    ]
